### ISSUE TITLE
complete reps + districts list 

### ISSUE THREAD

**Issue by amyleew** [thursdaynetwork/Hackathon_Gerrymandering#3]
@impreze @alliesaizan @mvaden - This data contains 1/2 of the house reps and their districts, but we need all 438. Can we complete this list?

[AHCA Accountability Town Halls](https://docs.google.com/spreadsheets/d/1EpB0e9NFGVDQvIlGyWu7g5MBY5U5kkXEM-dIEDjOiT8/edit#gid=0)

**Comment by alliesaizan** [comment]
Found a spreadsheet at the [house.gov](http://clerk.house.gov/member_info/) website. I can push it to Github tomorrow if you want it under "Data Sources".

**Comment by alliesaizan** [comment]
I put this spreadsheet (from this [source](http://clerk.house.gov/member_info/)) under the master branch, as it's fairly small. Thinking it would be a good resource for participants.
